# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

 use_frameworks!
pod 'Alamofire'
pod 'AlamofireImage'
pod 'RealmSwift'
pod 'IQKeyboardManagerSwift'

target 'CodeChallenge' do

end

target 'CodeChallengeTests' do

end

target 'CodeChallengeUITests' do

end

